### ISSUE TITLE
python3: Drop piksemel in favor of standard XML library

### ISSUE THREAD

**Issue by livingsilver94** [getsolus/package-management#20]
piksemel doesn't work with Python 3, plus we want to stay as close as possible to the standard library. I began converting the codebase to use the `xml` module. The codebase is pretty vast, I'm collecting here files to be processed.

These files contain the "piksemel" string:
- [x] scripts/make-changelog.py
- [x] pisi/specfile.py
- [x] pisi/pxml/xmlfile.py
- [x] pisi/db/installdb.py
- [x] pisi/db/packagedb.py
- [x] pisi/db/repodb.py
- [x] pisi/pxml/xmlext.py
- [x] scenarios/bug4211scen.py

Other files depending on piksemel without explicitly importing it:
- [x] pisi/db/componentdb.py

**Comment by livingsilver94** [comment]
Working on pisi/specfile.py currently.

**Comment by Zaryob** [comment]
and also if you deal a bit (specially you can use inary's xml part) you can get support with python's xml library's support but I'm especially recommending to use piksemel. Because python's xml library is sooooooooooooooooooo slow.

**Comment by livingsilver94** [comment]
We very much appreciate the effort you put into this and in fact we pulled in some commits of yours. However, please be aware that we would prefer to maintain compatibility with the Python standard library XML API and that, as such, our current preferred solution is the Python libxml binding. Should we find it slow, we'll probably switch over to libraries with similar API, if not drop-in replacements, like lxml.

**Comment by livingsilver94** [comment]
Done.
